# Generated by Django 3.2.4 on 2021-06-19 21:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('playerRace', models.CharField(choices=[('Terran', 'Terran'), ('Zerg', 'Zerg'), ('Protoss', 'Protoss')], max_length=10)),
                ('enemyRace', models.CharField(choices=[('Terran', 'Terran'), ('Zerg', 'Zerg'), ('Protoss', 'Protoss')], max_length=10)),
                ('text', models.TextField()),
                ('password', models.CharField(max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
