# Generated by Django 3.2.4 on 2021-06-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210622_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Normal', 'Normal'), ('Hard', 'Hard')], max_length=10),
        ),
    ]
