# Generated by Django 3.2.4 on 2021-06-22 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_strategy_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='password',
        ),
    ]
